#6 added convenience initalizers for TimeInterval
tbointeractive/bytes pull request #7
Opened 2017-11-28 13:20 UTC by achelsmar

2017-11-28 15:32 UTC, brototyp approved these changes

2017-11-28 15:33 UTC, brototyp requested changes
Can you add a line to the CHANGELOG.md?

2017-11-28 15:35 UTC, brototyp commented
Also: See my comment in #6.

2019-01-04 15:13 UTC, pstued commented
Implemented in #29

2019-01-04 15:13 UTC, closed without merging